// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiIGLvMQw-107J8qT0HAJXvaRVCo0AelE',
    appId: '1:441707655:web:cf74b8e6c23739e14d5c22',
    messagingSenderId: '441707655',
    projectId: 'aloha-dev-a9c32',
    authDomain: 'aloha-dev-a9c32.firebaseapp.com',
    storageBucket: 'aloha-dev-a9c32.appspot.com',
    measurementId: 'G-R1QE2QMEEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO-swPwHj8vcE_VN48aJifeP91QEuI_U8',
    appId: '1:441707655:android:da90984fd6e130794d5c22',
    messagingSenderId: '441707655',
    projectId: 'aloha-dev-a9c32',
    storageBucket: 'aloha-dev-a9c32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB10fuhbWj-_2ZFlXsqgXYRPQuO9Qa4qTw',
    appId: '1:441707655:ios:82dfc7cced47b0294d5c22',
    messagingSenderId: '441707655',
    projectId: 'aloha-dev-a9c32',
    storageBucket: 'aloha-dev-a9c32.appspot.com',
    iosClientId: '441707655-8l21mrf05sf3kbqum516l5uametg7vst.apps.googleusercontent.com',
    iosBundleId: 'com.example.aloha',
  );
}
