name: Aloha App CI

on:
  push:
    tags: 
      - release-*
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: action/checkout@v2
      - uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: '2.10.5'
          architecture: x64
      - run: flutter pub get
